### ISSUE TITLE
Package couldn't be found.

### ISSUE THREAD

**Issue by Vette1123** [bidah/react-native-vercel-ai#4]
Package declarations couldn't be found, i have used **npm i react-native-vercel-ai** but something is missing.

**Comment by bidah** [comment]
Could you please share the error or a reproducible example.

**Comment by Vette1123** [comment]
I can't use this

`import { useChat } from 'react-native-vercel-ai'`

as react-native-vercel-ai has not declaration, after installing your package.

**Comment by bidah** [comment]
added a fix to this in latest version. closing.
